version: '3.5'
services:
  api01: &api
    image: rinha-de-backend-2024-q1-javaslow
    container_name: rinha_backend_1
    environment:
      - SERVER_PORT=8080
      - CASSANDRA_PORT=9042
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_DC=datacenter1
    depends_on:
      - cassandra
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "60MB"

  api02:
    <<: *api
    container_name: rinha_backend_2
    environment:
      - SERVER_PORT=8081
      - CASSANDRA_PORT=9042
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_DC=datacenter1

  cassandra:
    image: 'cassandra:3.11.16'#2.1.20
    container_name: rinha_cassandra
    environment:
      - 'HEAP_NEWSIZE=128M'
      - 'MAX_HEAP_SIZE=350M'
    volumes:
      - ./db-init.sh:/db-init.sh
      - ./src/main/resources/schema.cql:/tmp/schema.cql
    command: "sh /db-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "350MB"

  nginx:
    image: nginx:latest
    container_name: rinha_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1